version: '2.3'

services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - "docker-compose-env/main.env"
    expose:
      - "8000"
      - "22"
    ports:
      - "8777:8000"
    stdin_open: true
    tty: true

volumes:
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume2/nfs_shared"
